version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ${DATABASE_HOST}
            port: ${DATABASE_PORT}
            user: ${DATABASE_USER}
            password: ${DATABASE_PASSWORD}
